### ISSUE TITLE
v0.4.0.0 release checklist

### ISSUE THREAD

**Issue by vaclavsvejcar** [vaclavsvejcar/headroom#70]
- [x] all tasks in corresponding [milestone](https://github.com/vaclavsvejcar/headroom/milestone/10) are tested and merged
- [x] _Hackage_ release is done
- [x] _GitHub_ release is done
- [x] _Homebrew_ release is done
- [x] _microsite_ documentation is uploaded
