### ISSUE TITLE
v0.4.2.0 checklist

### ISSUE THREAD

**Issue by vaclavsvejcar** [vaclavsvejcar/headroom#77]
- [x] all tasks in corresponding [milestone](https://github.com/vaclavsvejcar/headroom/milestone/12) are tested and merged
- [x] _Hackage_ release is done
- [x] _GitHub_ release is done
- [x] _Homebrew_ release is done
- [x] _microsite_ documentation is uploaded
